### PR TITLE
fix java imports

### PR DESCRIPTION
**Pull request by fabriziomoscon**
Hi,
your proposed solution works, but it was missing the `import` for `Resources`. So I opened it inside Android Studio and I using `Alt+Enter` it has fixed few things.

After that I could run my project as you explained in the issue.

I hope this is helpful

### CODE REVIEW

**Comment by ncnlinh** [comment]
@fabriziomoscon Thanks a lot for pointing out!
I think you submitted the PR into the wrong branch. The branch I used for the PR to luggg's project was ncnlinh:patch-1
Can you resubmit?

**Comment by ncnlinh** [comment]
@fabriziomoscon thanks for pointing out, I've merged #1 which fixed the problem!

**Comment by fabriziomoscon** [comment]
what about all the unused imports? Is there any reason why they are present? If not you should remove them.

**Comment by ncnlinh** [comment]
fixed! thanks

**Pull request closed without merging**
